"""
setup.py — py2app build config for TermLink
Usage:
    python3 setup.py py2app
"""
from setuptools import setup

APP      = ["main.py"]
DATA     = ["src/"]
OPTIONS  = {
    "argv_emulation": False,
    "iconfile": "assets/AppIcon.icns",   # generated by build_icns.py
    "packages": ["PyQt6"],
    "includes": ["zshrc_parser"],
    "excludes": ["tkinter"],
    "plist": {
        "CFBundleName":             "TermLink",
        "CFBundleDisplayName":      "TermLink",
        "CFBundleIdentifier":       "dev.termlink.app",
        "CFBundleVersion":          "1.0.0",
        "CFBundleShortVersionString":"1.0.0",
        "NSHumanReadableCopyright": "© 2026",
        "NSHighResolutionCapable":  True,
    },
}

setup(
    app=APP,
    data_files=DATA,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
