"""
setup.py — py2app build config for TermLink
Usage:
    python3 setup.py py2app

Version wird automatisch aus dem aktuellen Git-Tag gelesen (z.B. v1.1.0 → 1.1.0).
Kein Tag vorhanden → "0.0.0-dev".
"""
import subprocess
from pathlib import Path
from setuptools import setup


# ── Git-Version ermitteln und in src/version.py schreiben ─────────────────
def _git_version() -> str:
    try:
        tag = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0"],
            capture_output=True, text=True, check=True
        ).stdout.strip()
        return tag.lstrip("v")
    except Exception:
        pass
    try:
        # kein Tag → kurzer Commit-Hash
        sha = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True
        ).stdout.strip()
        return f"0.0.0-dev+{sha}"
    except Exception:
        return "0.0.0-dev"

VERSION = _git_version()
print(f"[setup.py] Building TermLink v{VERSION}")

version_file = Path(__file__).parent / "src" / "version.py"
version_file.write_text(
    f'# auto-generated by setup.py — do not edit\n__version__ = "{VERSION}"\n',
    encoding="utf-8",
)

# ── py2app config ──────────────────────────────────────────────────────────
APP     = ["main.py"]
DATA    = ["src/"]
OPTIONS = {
    "argv_emulation": False,
    "iconfile": "assets/AppIcon.icns",
    "packages": ["PyQt6"],
    "includes": ["zshrc_parser", "version"],
    "excludes": ["tkinter"],
    "plist": {
        "CFBundleName":              "TermLink",
        "CFBundleDisplayName":       "TermLink",
        "CFBundleIdentifier":        "dev.termlink.app",
        "CFBundleVersion":           VERSION,
        "CFBundleShortVersionString": VERSION,
        "NSHumanReadableCopyright":  "© 2026 klausinger",
        "NSHighResolutionCapable":   True,
    },
}

setup(
    app=APP,
    data_files=DATA,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
